name: Rust
on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: make test

  format:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: make test-format

  clippy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: make test-clippy
